name: CI/CD Branch Verify Pipeline

on:
  push:
    branches: [ "main", "develop", "master", "test/**" ]
    paths:
      - 'src/**'
      - 'pom.xml'
      - '.github/workflows/branch-verify.yaml'
  pull_request:
    branches: [ "main", "master" ]

jobs:
  BRANCH-VERIFY:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: maven

    - name: Set vars outputs
      id: vars
      run: |
         echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
         echo "CURRENT_TIMESTAMP=$(date +'%Y-%m-%dT%H%M%SZ')" >> $GITHUB_OUTPUT

    - name: Verify with Maven
      working-directory: docker-hello-world-spring-boot
      run: mvn clean verify

    - name: Package with Maven
      working-directory: docker-hello-world-spring-boot
      run: mvn clean package -Dmaven.test.skip
